version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/cookbook
      - bundler-cache:/cookbook/vendor/bundle
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CHEF_LICENSE=accept-silent
      - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  bundler-cache: